name: Deploy API to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Conectar al servidor y ejecutar el script
        uses: appleboy/ssh-action@v1.0.3 
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Todo lo que está debajo de 'script:' se ejecuta DENTRO de tu servidor AWS
            cd ~/PatitasBackend
            ./deploy.sh